### ISSUE TITLE
block breaking

### ISSUE THREAD

**Issue by MankyHamster** [LeCloutPanda/ConcretePlus#2]
Hi, been testing this (AWESOME) mod for the update of our server to 1.19. Whereas in 1.18 we could mine at the same rate with a pickaxe as concrete - it's now taking around the same time as Obsidian. Is it possible to make these the same please?

**Comment by LeCloutPanda** [comment]
Fixed and can be found here: https://www.curseforge.com/minecraft/mc-mods/concrete-plus/files/3855878
